behaviors:
  MazeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 256
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      curiosity:
        strength: 0.3
        gamma: 0.995
        encoding_size: 128
        learning_rate: 0.0003
      #gail:
       #gamma: 0.99
       #strength: 0.5
       #encoding_size: 1024
       #learning_rate: 0.0003
       #use_actions: false
       #use_vail: false
       #demo_path: ML_Demo/MazeDemo.demo
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 5000
    threaded: true
